const $=s=>document.querySelector(s), feed=$('#feed');let recognition=null,listening=false;const synth=window.speechSynthesis;
function log(who,msg){const p=document.createElement('p');p.innerHTML=`<b>${who}:</b> ${msg}`;feed.prepend(p)}
function speak(text){if(!synth)return; synth.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='hi-IN';u.rate=.96;u.pitch=.9;synth.speak(u);log('NOVA',text)}
function answer(q){q=q.toLowerCase();if(q.includes('समय')||q.includes('time'))return `अभी ${new Intl.DateTimeFormat('hi-IN',{timeStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())} है।`;if(q.includes('मौसम')||q.includes('weather'))return 'मौसम के लिए इस NOVA dashboard को live weather API से जोड़ा जा सकता है। Browser location permission मिलने पर इसे live किया जा सकता है।';if(q.includes('जोक')||q.includes('हंसा'))return 'Mohit, मेरा processor इतना तेज है कि कभी-कभी मैं खुद से पूछता हूँ—मैं AI हूँ या Wi-Fi का रिश्तेदार? 😄';if(q.includes('मूड')||q.includes('happy'))return 'आज का mission: tension कम, confidence ज्यादा. तुम कर सकते हो, boss! 😎';if(q.includes('मोटिवेट'))return 'एक छोटा कदम भी progress है. आज बस एक काम पूरा करो, फिर अगला NOVA संभाल लेगा।';if(q.includes('हेल्प')||q.includes('मदद'))return 'मैं time, voice, browser commands और phone NOVA app के supported controls में मदद कर सकता हूँ।';return 'मैंने तुम्हारी बात सुनी। General topic answers के लिए NOVA Android app में secure AI Brain connect किया जा सकता है।'}
function ask(){const q=$('#q').value.trim();if(!q)return;log('YOU',q);$('#q').value='';speak(answer(q))}
$('#ask').onclick=ask;$('#q').addEventListener('keydown',e=>{if(e.key==='Enter')ask()});document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{$('#q').value=b.dataset.cmd;ask()});
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(window.Android){if(['whatsapp','youtube','instagram','chrome','camera'].includes(a))Android.openApp(a);else if(a==='wifi'||a==='bluetooth')Android.openSettings(a);else Android.openSettings('general')}else speak(`${a} खोलने के लिए NOVA Android app इस्तेमाल करें।`)});
function start(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){speak('इस browser में microphone speech recognition उपलब्ध नहीं है।');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.lang='hi-IN';recognition.continuous=true;recognition.interimResults=false;recognition.onstart=()=>{listening=true;document.body.classList.add('listening');$('#status').textContent='LISTENING';$('#voiceState').textContent='ON'};recognition.onend=()=>{if(listening)try{recognition.start()}catch(e){}};recognition.onerror=()=>{};recognition.onresult=e=>{const t=e.results[e.results.length-1][0].transcript;log('YOU',t);const x=t.toLowerCase();if(x.includes('nova')||x.includes('नोवा')){const q=x.replace(/nova|नोवा/gi,'').trim();speak(q?answer(q):'हाँ Mohit, मैं सुन रहा हूँ।')}};try{recognition.start()}catch(e){}}
function stop(){listening=false;document.body.classList.remove('listening');$('#status').textContent='STANDBY';$('#voiceState').textContent='OFF';recognition?.stop()}
$('#mic').onclick=()=>listening?stop():start();$('#speak').onclick=()=>speak('हाँ Mohit, NOVA online है।');$('#theme').onclick=()=>{document.documentElement.style.setProperty('--c',getComputedStyle(document.documentElement).getPropertyValue('--c').trim()==='#54e8ff'?'#ff6adf':'#54e8ff');document.documentElement.style.setProperty('--c2','#9b7bff')};
setInterval(()=>{$('#clock').textContent=new Intl.DateTimeFormat('en-IN',{timeStyle:'medium',hour12:false,timeZone:'Asia/Kolkata'}).format(new Date());$('#date').textContent=new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())},500);if(!navigator.onLine)$('#network').textContent='OFFLINE';
